FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /build
COPY pom.xml .
COPY src ./src
COPY test ./test
RUN mvn -DskipTests package

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=build /build/target/kungfuchess-matchmaker.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
